// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC

#ifndef _EIC_UI_H
#define _EIC_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_currentX;
extern lv_obj_t * ui_currentY;
extern lv_obj_t * ui_currentYaw;
void ui_event_enableMotorSwitch(lv_event_t * e);
extern lv_obj_t * ui_enableMotorSwitch;
extern lv_obj_t * ui_Label6;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label9;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_servo0angle;
extern lv_obj_t * ui_servo1angle;
extern lv_obj_t * ui_servo2angle;
extern lv_obj_t * ui_servo3angle;
extern lv_obj_t * ui_servo4angle;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label17;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_batteryPercentBar;
extern lv_obj_t * ui_Label52;
// CUSTOM VARIABLES

// SCREEN: ui_otaScreen
void ui_otaScreen_screen_init(void);
extern lv_obj_t * ui_otaScreen;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_otaPercent;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_wifiStatusLabel;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_ipAddressLabel;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_otaStatusLabel;
void ui_event_Button24(lv_event_t * e);
extern lv_obj_t * ui_Button24;
extern lv_obj_t * ui_Label50;
void ui_event_Button26(lv_event_t * e);
extern lv_obj_t * ui_Button26;
extern lv_obj_t * ui_Label51;
// CUSTOM VARIABLES

// SCREEN: ui_motionScreen
void ui_motionScreen_screen_init(void);
extern lv_obj_t * ui_motionScreen;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_TabView4;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_moving_pos_Kp;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_moving_pos_Ki;
extern lv_obj_t * ui_moving_pos_Kd;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label27;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label28;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label29;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label30;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label31;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_moving_yaw_Kp;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_moving_yaw_Ki;
extern lv_obj_t * ui_moving_yaw_Kd;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label35;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label36;
void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label37;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label38;
void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Label39;
void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Label40;
void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_TabPage4;
extern lv_obj_t * ui_moving_spd_linear;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_moving_spd_angular;
extern lv_obj_t * ui_Label43;
void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui_Label45;
void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
extern lv_obj_t * ui_Label46;
void ui_event_Button23(lv_event_t * e);
extern lv_obj_t * ui_Button23;
extern lv_obj_t * ui_Label47;
void ui_event_Button25(lv_event_t * e);
extern lv_obj_t * ui_Button25;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Label48;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_bigchinese);
LV_FONT_DECLARE(ui_font_chinese);
LV_FONT_DECLARE(ui_font_taskcode);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
