// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void lockCurrentPos(lv_event_t * e);
void toNextPos(lv_event_t * e);
void enableMotor(lv_event_t * e);
void armTestFunc(lv_event_t * e);
void servoSetOringin(lv_event_t * e);
void stopServo(lv_event_t * e);
void startOTA(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
