// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC_release

#include "ui.h"
#include "mainSequence.h"
void uiStartMainSequence(lv_event_t * e)
{
	startMainSequence();
}
