// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC

#include "ui.h"

void ui_motionScreen_screen_init(void)
{
    ui_motionScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_motionScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_motionScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color4);
    ui_object_set_themeable_style_property(ui_motionScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color4);

    ui_Button7 = lv_button_create(ui_motionScreen);
    lv_obj_set_width(ui_Button7, 50);
    lv_obj_set_height(ui_Button7, 50);
    lv_obj_set_x(ui_Button7, -125);
    lv_obj_set_y(ui_Button7, -90);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);

    ui_Label19 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "返回");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8 = lv_button_create(ui_motionScreen);
    lv_obj_set_width(ui_Button8, 50);
    lv_obj_set_height(ui_Button8, 50);
    lv_obj_set_x(ui_Button8, -125);
    lv_obj_set_y(ui_Button8, 90);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_Label21 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "应用\n更改");
    lv_obj_set_style_text_font(ui_Label21, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_button_create(ui_motionScreen);
    lv_obj_set_width(ui_Button9, 50);
    lv_obj_set_height(ui_Button9, 50);
    lv_obj_set_x(ui_Button9, -125);
    lv_obj_set_y(ui_Button9, -30);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "test1");

    ui_TabView4 = lv_tabview_create(ui_motionScreen);
    lv_tabview_set_tab_bar_size(ui_TabView4, 30);
    lv_obj_set_width(ui_TabView4, 250);
    lv_obj_set_height(ui_TabView4, 166);
    lv_obj_set_x(ui_TabView4, 35);
    lv_obj_set_y(ui_TabView4, 15);
    lv_obj_set_align(ui_TabView4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView4, "POS");
    lv_obj_remove_flag(ui_TabPage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_moving_pos_Kp = lv_spinbox_create(ui_TabPage2);
    lv_obj_set_width(ui_moving_pos_Kp, 80);
    lv_obj_set_height(ui_moving_pos_Kp, 36);
    lv_obj_set_x(ui_moving_pos_Kp, -20);
    lv_obj_set_y(ui_moving_pos_Kp, -45);
    lv_obj_set_align(ui_moving_pos_Kp, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_moving_pos_Kp, 6, 3);
    lv_spinbox_set_range(ui_moving_pos_Kp, 0, 999999);
    lv_spinbox_set_cursor_pos(ui_moving_pos_Kp, 1 - 1);

    ui_Label26 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -90);
    lv_obj_set_y(ui_Label26, -45);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "POS Kp");

    ui_moving_pos_Ki = lv_spinbox_create(ui_TabPage2);
    lv_obj_set_width(ui_moving_pos_Ki, 80);
    lv_obj_set_height(ui_moving_pos_Ki, 36);
    lv_obj_set_x(ui_moving_pos_Ki, -20);
    lv_obj_set_y(ui_moving_pos_Ki, 0);
    lv_obj_set_align(ui_moving_pos_Ki, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_moving_pos_Ki, 6, 3);
    lv_spinbox_set_range(ui_moving_pos_Ki, 0, 999999);
    lv_spinbox_set_cursor_pos(ui_moving_pos_Ki, 1 - 1);

    ui_moving_pos_Kd = lv_spinbox_create(ui_TabPage2);
    lv_obj_set_width(ui_moving_pos_Kd, 80);
    lv_obj_set_height(ui_moving_pos_Kd, 36);
    lv_obj_set_x(ui_moving_pos_Kd, -20);
    lv_obj_set_y(ui_moving_pos_Kd, 45);
    lv_obj_set_align(ui_moving_pos_Kd, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_moving_pos_Kd, 6, 3);
    lv_spinbox_set_range(ui_moving_pos_Kd, 0, 999999);
    lv_spinbox_set_cursor_pos(ui_moving_pos_Kd, 1 - 1);

    ui_Label2 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -90);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "POS Ki");

    ui_Label3 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -90);
    lv_obj_set_y(ui_Label3, 45);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "POS Kd");

    ui_Button12 = lv_button_create(ui_TabPage2);
    lv_obj_set_width(ui_Button12, 34);
    lv_obj_set_height(ui_Button12, 34);
    lv_obj_set_x(ui_Button12, 45);
    lv_obj_set_y(ui_Button12, -45);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);

    ui_Label27 = lv_label_create(ui_Button12);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "+");

    ui_Button1 = lv_button_create(ui_TabPage2);
    lv_obj_set_width(ui_Button1, 34);
    lv_obj_set_height(ui_Button1, 34);
    lv_obj_set_x(ui_Button1, 90);
    lv_obj_set_y(ui_Button1, -45);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_Label28 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "-");

    ui_Button2 = lv_button_create(ui_TabPage2);
    lv_obj_set_width(ui_Button2, 34);
    lv_obj_set_height(ui_Button2, 34);
    lv_obj_set_x(ui_Button2, 45);
    lv_obj_set_y(ui_Button2, 0);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);

    ui_Label29 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "+");

    ui_Button5 = lv_button_create(ui_TabPage2);
    lv_obj_set_width(ui_Button5, 34);
    lv_obj_set_height(ui_Button5, 34);
    lv_obj_set_x(ui_Button5, 45);
    lv_obj_set_y(ui_Button5, 45);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);

    ui_Label30 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "+");

    ui_Button13 = lv_button_create(ui_TabPage2);
    lv_obj_set_width(ui_Button13, 34);
    lv_obj_set_height(ui_Button13, 34);
    lv_obj_set_x(ui_Button13, 90);
    lv_obj_set_y(ui_Button13, 0);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button13, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button13, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_Label31 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "-");

    ui_Button14 = lv_button_create(ui_TabPage2);
    lv_obj_set_width(ui_Button14, 34);
    lv_obj_set_height(ui_Button14, 34);
    lv_obj_set_x(ui_Button14, 90);
    lv_obj_set_y(ui_Button14, 45);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button14, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button14, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_Label32 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "-");

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView4, "YAW");
    lv_obj_remove_flag(ui_TabPage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_moving_yaw_Kp = lv_spinbox_create(ui_TabPage3);
    lv_obj_set_width(ui_moving_yaw_Kp, 80);
    lv_obj_set_height(ui_moving_yaw_Kp, 36);
    lv_obj_set_x(ui_moving_yaw_Kp, -20);
    lv_obj_set_y(ui_moving_yaw_Kp, -45);
    lv_obj_set_align(ui_moving_yaw_Kp, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_moving_yaw_Kp, 6, 3);
    lv_spinbox_set_range(ui_moving_yaw_Kp, 0, 999999);
    lv_spinbox_set_cursor_pos(ui_moving_yaw_Kp, 1 - 1);

    ui_Label33 = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -90);
    lv_obj_set_y(ui_Label33, -45);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "YAW Kp");

    ui_moving_yaw_Ki = lv_spinbox_create(ui_TabPage3);
    lv_obj_set_width(ui_moving_yaw_Ki, 80);
    lv_obj_set_height(ui_moving_yaw_Ki, 36);
    lv_obj_set_x(ui_moving_yaw_Ki, -20);
    lv_obj_set_y(ui_moving_yaw_Ki, 0);
    lv_obj_set_align(ui_moving_yaw_Ki, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_moving_yaw_Ki, 6, 3);
    lv_spinbox_set_range(ui_moving_yaw_Ki, 0, 999999);
    lv_spinbox_set_cursor_pos(ui_moving_yaw_Ki, 1 - 1);

    ui_moving_yaw_Kd = lv_spinbox_create(ui_TabPage3);
    lv_obj_set_width(ui_moving_yaw_Kd, 80);
    lv_obj_set_height(ui_moving_yaw_Kd, 36);
    lv_obj_set_x(ui_moving_yaw_Kd, -20);
    lv_obj_set_y(ui_moving_yaw_Kd, 45);
    lv_obj_set_align(ui_moving_yaw_Kd, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_moving_yaw_Kd, 6, 3);
    lv_spinbox_set_range(ui_moving_yaw_Kd, 0, 999999);
    lv_spinbox_set_cursor_pos(ui_moving_yaw_Kd, 1 - 1);

    ui_Label34 = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, -90);
    lv_obj_set_y(ui_Label34, 0);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "YAW Ki");

    ui_Label35 = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, -90);
    lv_obj_set_y(ui_Label35, 45);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "YAW Kd");

    ui_Button15 = lv_button_create(ui_TabPage3);
    lv_obj_set_width(ui_Button15, 34);
    lv_obj_set_height(ui_Button15, 34);
    lv_obj_set_x(ui_Button15, 45);
    lv_obj_set_y(ui_Button15, -45);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button15, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button15, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);

    ui_Label36 = lv_label_create(ui_Button15);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "+");

    ui_Button16 = lv_button_create(ui_TabPage3);
    lv_obj_set_width(ui_Button16, 34);
    lv_obj_set_height(ui_Button16, 34);
    lv_obj_set_x(ui_Button16, 90);
    lv_obj_set_y(ui_Button16, -45);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button16, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button16, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_Label37 = lv_label_create(ui_Button16);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "-");

    ui_Button17 = lv_button_create(ui_TabPage3);
    lv_obj_set_width(ui_Button17, 34);
    lv_obj_set_height(ui_Button17, 34);
    lv_obj_set_x(ui_Button17, 45);
    lv_obj_set_y(ui_Button17, 0);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button17, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button17, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);

    ui_Label38 = lv_label_create(ui_Button17);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "+");

    ui_Button18 = lv_button_create(ui_TabPage3);
    lv_obj_set_width(ui_Button18, 34);
    lv_obj_set_height(ui_Button18, 34);
    lv_obj_set_x(ui_Button18, 45);
    lv_obj_set_y(ui_Button18, 45);
    lv_obj_set_align(ui_Button18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button18, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button18, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);

    ui_Label39 = lv_label_create(ui_Button18);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "+");

    ui_Button19 = lv_button_create(ui_TabPage3);
    lv_obj_set_width(ui_Button19, 34);
    lv_obj_set_height(ui_Button19, 34);
    lv_obj_set_x(ui_Button19, 90);
    lv_obj_set_y(ui_Button19, 0);
    lv_obj_set_align(ui_Button19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button19, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button19, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_Label40 = lv_label_create(ui_Button19);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "-");

    ui_Button20 = lv_button_create(ui_TabPage3);
    lv_obj_set_width(ui_Button20, 34);
    lv_obj_set_height(ui_Button20, 34);
    lv_obj_set_x(ui_Button20, 90);
    lv_obj_set_y(ui_Button20, 45);
    lv_obj_set_align(ui_Button20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button20, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button20, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_Label41 = lv_label_create(ui_Button20);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "-");

    ui_TabPage4 = lv_tabview_add_tab(ui_TabView4, "SPD");
    lv_obj_remove_flag(ui_TabPage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_moving_spd_linear = lv_spinbox_create(ui_TabPage4);
    lv_obj_set_width(ui_moving_spd_linear, 80);
    lv_obj_set_height(ui_moving_spd_linear, 36);
    lv_obj_set_x(ui_moving_spd_linear, -20);
    lv_obj_set_y(ui_moving_spd_linear, -45);
    lv_obj_set_align(ui_moving_spd_linear, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_moving_spd_linear, 6, 5);
    lv_spinbox_set_range(ui_moving_spd_linear, 0, 999999);
    lv_spinbox_set_cursor_pos(ui_moving_spd_linear, 1 - 1);

    ui_Label42 = lv_label_create(ui_TabPage4);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, -90);
    lv_obj_set_y(ui_Label42, -45);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "linear\n(mm/s)");

    ui_moving_spd_angular = lv_spinbox_create(ui_TabPage4);
    lv_obj_set_width(ui_moving_spd_angular, 80);
    lv_obj_set_height(ui_moving_spd_angular, 36);
    lv_obj_set_x(ui_moving_spd_angular, -20);
    lv_obj_set_y(ui_moving_spd_angular, 25);
    lv_obj_set_align(ui_moving_spd_angular, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_moving_spd_angular, 6, 3);
    lv_spinbox_set_range(ui_moving_spd_angular, 0, 999999);
    lv_spinbox_set_cursor_pos(ui_moving_spd_angular, 1 - 1);

    ui_Label43 = lv_label_create(ui_TabPage4);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, -90);
    lv_obj_set_y(ui_Label43, 25);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "angular\n(°/s)");

    ui_Button21 = lv_button_create(ui_TabPage4);
    lv_obj_set_width(ui_Button21, 34);
    lv_obj_set_height(ui_Button21, 34);
    lv_obj_set_x(ui_Button21, 45);
    lv_obj_set_y(ui_Button21, -45);
    lv_obj_set_align(ui_Button21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button21, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button21, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);

    ui_Label45 = lv_label_create(ui_Button21);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "+");

    ui_Button22 = lv_button_create(ui_TabPage4);
    lv_obj_set_width(ui_Button22, 34);
    lv_obj_set_height(ui_Button22, 34);
    lv_obj_set_x(ui_Button22, 90);
    lv_obj_set_y(ui_Button22, -45);
    lv_obj_set_align(ui_Button22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button22, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button22, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_Label46 = lv_label_create(ui_Button22);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "-");

    ui_Button23 = lv_button_create(ui_TabPage4);
    lv_obj_set_width(ui_Button23, 34);
    lv_obj_set_height(ui_Button23, 34);
    lv_obj_set_x(ui_Button23, 45);
    lv_obj_set_y(ui_Button23, 25);
    lv_obj_set_align(ui_Button23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button23, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button23, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button23, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);

    ui_Label47 = lv_label_create(ui_Button23);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "+");

    ui_Button25 = lv_button_create(ui_TabPage4);
    lv_obj_set_width(ui_Button25, 34);
    lv_obj_set_height(ui_Button25, 34);
    lv_obj_set_x(ui_Button25, 90);
    lv_obj_set_y(ui_Button25, 25);
    lv_obj_set_align(ui_Button25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button25, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button25, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button25, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_Label49 = lv_label_create(ui_Button25);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "-");

    ui_Button10 = lv_button_create(ui_motionScreen);
    lv_obj_set_width(ui_Button10, 50);
    lv_obj_set_height(ui_Button10, 50);
    lv_obj_set_x(ui_Button10, -125);
    lv_obj_set_y(ui_Button10, 30);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "test2");

    ui_Switch1 = lv_switch_create(ui_motionScreen);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 26);
    lv_obj_set_y(ui_Switch1, -100);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_Switch1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Switch1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);
    ui_object_set_themeable_style_property(ui_Switch1, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Switch1, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_object_set_themeable_style_property(ui_Switch1, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Switch1, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_Label44 = lv_label_create(ui_motionScreen);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, -42);
    lv_obj_set_y(ui_Label44, -100);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "MOVING");

    ui_Label48 = lv_label_create(ui_motionScreen);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label48, 99);
    lv_obj_set_y(ui_Label48, -100);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "HOLDING");

    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button19, ui_event_Button19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button20, ui_event_Button20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button21, ui_event_Button21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button22, ui_event_Button22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button23, ui_event_Button23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button25, ui_event_Button25, LV_EVENT_ALL, NULL);

}
