// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC

#include "ui.h"

void ui_otaScreen_screen_init(void)
{
    ui_otaScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_otaScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_otaScreen);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -105);
    lv_obj_set_y(ui_Label18, -85);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "WiFi:");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiStatusLabel = lv_label_create(ui_otaScreen);
    lv_obj_set_width(ui_wifiStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiStatusLabel, -54);
    lv_obj_set_y(ui_wifiStatusLabel, -85);
    lv_obj_set_align(ui_wifiStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiStatusLabel, "未连接");
    lv_obj_set_style_text_font(ui_wifiStatusLabel, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_otaScreen);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -4);
    lv_obj_set_y(ui_Label20, -85);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "IP:");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ipAddressLabel = lv_label_create(ui_otaScreen);
    lv_obj_set_width(ui_ipAddressLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ipAddressLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ipAddressLabel, 71);
    lv_obj_set_y(ui_ipAddressLabel, -85);
    lv_obj_set_align(ui_ipAddressLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ipAddressLabel, "N/A");
    lv_obj_set_style_text_font(ui_ipAddressLabel, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_otaScreen);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -2);
    lv_obj_set_y(ui_Label22, 30);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "OTA状态:");
    lv_obj_set_style_text_font(ui_Label22, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_otaStatusLabel = lv_label_create(ui_otaScreen);
    lv_obj_set_width(ui_otaStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_otaStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_otaStatusLabel, 0);
    lv_obj_set_y(ui_otaStatusLabel, 55);
    lv_obj_set_align(ui_otaStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_otaStatusLabel, "N/A");
    lv_obj_set_style_text_font(ui_otaStatusLabel, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_otaScreen);
    lv_obj_set_width(ui_Panel3, 280);
    lv_obj_set_height(ui_Panel3, 75);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, -29);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_otaPercent = lv_bar_create(ui_Panel3);
    lv_obj_set_width(ui_otaPercent, 263);
    lv_obj_set_height(ui_otaPercent, 21);
    lv_obj_set_x(ui_otaPercent, 0);
    lv_obj_set_y(ui_otaPercent, 15);
    lv_obj_set_align(ui_otaPercent, LV_ALIGN_CENTER);

    ui_object_set_themeable_style_property(ui_otaPercent, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_otaPercent, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_otaPercent, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_otaPercent,
                                                                                                 lv_obj_get_style_pad_right(ui_otaPercent, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label24 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 0);
    lv_obj_set_y(ui_Label24, -15);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "OTA进度:");
    lv_obj_set_style_text_font(ui_Label24, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

}
