// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC

#include "ui.h"

void ui_servoTestScreen_screen_init(void)
{
    ui_servoTestScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_servoTestScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel6 = lv_obj_create(ui_servoTestScreen);
    lv_obj_set_width(ui_Panel6, 99);
    lv_obj_set_height(ui_Panel6, 116);
    lv_obj_set_x(ui_Panel6, -97);
    lv_obj_set_y(ui_Panel6, 8);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label56 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label56, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label56, -5);
    lv_obj_set_y(ui_Label56, -40);
    lv_obj_set_align(ui_Label56, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label56, "0:");
    lv_obj_set_style_text_font(ui_Label56, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -5);
    lv_obj_set_y(ui_Label7, -20);
    lv_obj_set_align(ui_Label7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label7, "1:");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -5);
    lv_obj_set_y(ui_Label8, 0);
    lv_obj_set_align(ui_Label8, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label8, "2:");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label53, -5);
    lv_obj_set_y(ui_Label53, 20);
    lv_obj_set_align(ui_Label53, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label53, "3:");
    lv_obj_set_style_text_font(ui_Label53, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label54, -5);
    lv_obj_set_y(ui_Label54, 40);
    lv_obj_set_align(ui_Label54, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label54, "4:");
    lv_obj_set_style_text_font(ui_Label54, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_servo0angle = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_servo0angle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo0angle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo0angle, 12);
    lv_obj_set_y(ui_servo0angle, -40);
    lv_obj_set_align(ui_servo0angle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo0angle, "0");

    ui_servo1angle = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_servo1angle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo1angle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo1angle, 12);
    lv_obj_set_y(ui_servo1angle, -20);
    lv_obj_set_align(ui_servo1angle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo1angle, "0");

    ui_servo2angle = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_servo2angle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo2angle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo2angle, 12);
    lv_obj_set_y(ui_servo2angle, 0);
    lv_obj_set_align(ui_servo2angle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo2angle, "0");

    ui_servo3angle = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_servo3angle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo3angle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo3angle, 12);
    lv_obj_set_y(ui_servo3angle, 20);
    lv_obj_set_align(ui_servo3angle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo3angle, "0");

    ui_servo4angle = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_servo4angle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo4angle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo4angle, 12);
    lv_obj_set_y(ui_servo4angle, 40);
    lv_obj_set_align(ui_servo4angle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo4angle, "0");

    ui_Button27 = lv_button_create(ui_servoTestScreen);
    lv_obj_set_width(ui_Button27, 100);
    lv_obj_set_height(ui_Button27, 50);
    lv_obj_set_x(ui_Button27, 95);
    lv_obj_set_y(ui_Button27, -85);
    lv_obj_set_align(ui_Button27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button27, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button27, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button27, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_Label10 = lv_label_create(ui_Button27);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "更新");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button28 = lv_button_create(ui_servoTestScreen);
    lv_obj_set_width(ui_Button28, 100);
    lv_obj_set_height(ui_Button28, 50);
    lv_obj_set_x(ui_Button28, -95);
    lv_obj_set_y(ui_Button28, -85);
    lv_obj_set_align(ui_Button28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button28, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button28, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button28, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);

    ui_Label13 = lv_label_create(ui_Button28);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "返回");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_servoTestScreen);
    lv_obj_set_width(ui_Panel2, 82);
    lv_obj_set_height(ui_Panel2, 52);
    lv_obj_set_x(ui_Panel2, -1);
    lv_obj_set_y(ui_Panel2, -84);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -20);
    lv_obj_set_y(ui_Label14, -16);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "x:");

    ui_Label15 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -20);
    lv_obj_set_y(ui_Label15, 0);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "y:");

    ui_Label16 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -20);
    lv_obj_set_y(ui_Label16, 16);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "z:");

    ui_armX = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_armX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_armX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_armX, 15);
    lv_obj_set_y(ui_armX, -16);
    lv_obj_set_align(ui_armX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_armX, "0");

    ui_armY = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_armY, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_armY, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_armY, 15);
    lv_obj_set_y(ui_armY, 0);
    lv_obj_set_align(ui_armY, LV_ALIGN_CENTER);
    lv_label_set_text(ui_armY, "0");

    ui_armZ = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_armZ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_armZ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_armZ, 15);
    lv_obj_set_y(ui_armZ, 16);
    lv_obj_set_align(ui_armZ, LV_ALIGN_CENTER);
    lv_label_set_text(ui_armZ, "0");

    ui_armXSlider = lv_slider_create(ui_servoTestScreen);
    lv_slider_set_range(ui_armXSlider, -400, 400);
    lv_slider_set_value(ui_armXSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_armXSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_armXSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_armXSlider, 150);
    lv_obj_set_height(ui_armXSlider, 10);
    lv_obj_set_x(ui_armXSlider, 60);
    lv_obj_set_y(ui_armXSlider, -40);
    lv_obj_set_align(ui_armXSlider, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_armXSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_armXSlider,
                                                                                                 lv_obj_get_style_pad_right(ui_armXSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label57 = lv_label_create(ui_servoTestScreen);
    lv_obj_set_width(ui_Label57, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label57, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label57, -30);
    lv_obj_set_y(ui_Label57, -40);
    lv_obj_set_align(ui_Label57, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label57, "X:");

    ui_armYSlider = lv_slider_create(ui_servoTestScreen);
    lv_slider_set_range(ui_armYSlider, -400, 400);
    lv_slider_set_value(ui_armYSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_armYSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_armYSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_armYSlider, 150);
    lv_obj_set_height(ui_armYSlider, 10);
    lv_obj_set_x(ui_armYSlider, 60);
    lv_obj_set_y(ui_armYSlider, -10);
    lv_obj_set_align(ui_armYSlider, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_armYSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_armYSlider,
                                                                                                 lv_obj_get_style_pad_right(ui_armYSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_armZSlider = lv_slider_create(ui_servoTestScreen);
    lv_slider_set_range(ui_armZSlider, -100, 300);
    lv_slider_set_value(ui_armZSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_armZSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_armZSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_armZSlider, 150);
    lv_obj_set_height(ui_armZSlider, 10);
    lv_obj_set_x(ui_armZSlider, 60);
    lv_obj_set_y(ui_armZSlider, 20);
    lv_obj_set_align(ui_armZSlider, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_armZSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_armZSlider,
                                                                                                 lv_obj_get_style_pad_right(ui_armZSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label58 = lv_label_create(ui_servoTestScreen);
    lv_obj_set_width(ui_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label58, -30);
    lv_obj_set_y(ui_Label58, -10);
    lv_obj_set_align(ui_Label58, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label58, "Y:");

    ui_Label59 = lv_label_create(ui_servoTestScreen);
    lv_obj_set_width(ui_Label59, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label59, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label59, -30);
    lv_obj_set_y(ui_Label59, 20);
    lv_obj_set_align(ui_Label59, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label59, "Z:");

    ui_Label60 = lv_label_create(ui_servoTestScreen);
    lv_obj_set_width(ui_Label60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label60, -30);
    lv_obj_set_y(ui_Label60, 50);
    lv_obj_set_align(ui_Label60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label60, "T");

    ui_armIntervalSpinbox = lv_spinbox_create(ui_servoTestScreen);
    lv_obj_set_width(ui_armIntervalSpinbox, 58);
    lv_obj_set_height(ui_armIntervalSpinbox, 36);
    lv_obj_set_x(ui_armIntervalSpinbox, 25);
    lv_obj_set_y(ui_armIntervalSpinbox, 50);
    lv_obj_set_align(ui_armIntervalSpinbox, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_armIntervalSpinbox, 4, 0);
    lv_spinbox_set_range(ui_armIntervalSpinbox, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_armIntervalSpinbox, 1 - 1);
    lv_spinbox_set_value(ui_armIntervalSpinbox, 1000);

    ui_Button30 = lv_button_create(ui_servoTestScreen);
    lv_obj_set_width(ui_Button30, 34);
    lv_obj_set_height(ui_Button30, 34);
    lv_obj_set_x(ui_Button30, 75);
    lv_obj_set_y(ui_Button30, 50);
    lv_obj_set_align(ui_Button30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button30, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button30, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button30, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);

    ui_Label61 = lv_label_create(ui_Button30);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label61, "+");

    ui_Button31 = lv_button_create(ui_servoTestScreen);
    lv_obj_set_width(ui_Button31, 34);
    lv_obj_set_height(ui_Button31, 34);
    lv_obj_set_x(ui_Button31, 115);
    lv_obj_set_y(ui_Button31, 50);
    lv_obj_set_align(ui_Button31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button31, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button31, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button31, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_Label62 = lv_label_create(ui_Button31);
    lv_obj_set_width(ui_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label62, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label62, "-");

    ui_Label63 = lv_label_create(ui_servoTestScreen);
    lv_obj_set_width(ui_Label63, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label63, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label63, -44);
    lv_obj_set_y(ui_Label63, 90);
    lv_obj_set_align(ui_Label63, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label63, "ACC/DEC");

    ui_armACC_DECSpinbox = lv_spinbox_create(ui_servoTestScreen);
    lv_obj_set_width(ui_armACC_DECSpinbox, 58);
    lv_obj_set_height(ui_armACC_DECSpinbox, 36);
    lv_obj_set_x(ui_armACC_DECSpinbox, 25);
    lv_obj_set_y(ui_armACC_DECSpinbox, 90);
    lv_obj_set_align(ui_armACC_DECSpinbox, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_armACC_DECSpinbox, 4, 0);
    lv_spinbox_set_range(ui_armACC_DECSpinbox, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_armACC_DECSpinbox, 1 - 1);
    lv_spinbox_set_value(ui_armACC_DECSpinbox, 100);

    ui_Button32 = lv_button_create(ui_servoTestScreen);
    lv_obj_set_width(ui_Button32, 34);
    lv_obj_set_height(ui_Button32, 34);
    lv_obj_set_x(ui_Button32, 75);
    lv_obj_set_y(ui_Button32, 90);
    lv_obj_set_align(ui_Button32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button32, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button32, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button32, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);

    ui_Label64 = lv_label_create(ui_Button32);
    lv_obj_set_width(ui_Label64, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label64, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label64, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label64, "+");

    ui_Button33 = lv_button_create(ui_servoTestScreen);
    lv_obj_set_width(ui_Button33, 34);
    lv_obj_set_height(ui_Button33, 34);
    lv_obj_set_x(ui_Button33, 115);
    lv_obj_set_y(ui_Button33, 90);
    lv_obj_set_align(ui_Button33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button33, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button33, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button33, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_Label65 = lv_label_create(ui_Button33);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label65, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label65, "-");

    ui_uiSetClawSwitch = lv_switch_create(ui_servoTestScreen);
    lv_obj_set_width(ui_uiSetClawSwitch, 50);
    lv_obj_set_height(ui_uiSetClawSwitch, 25);
    lv_obj_set_x(ui_uiSetClawSwitch, -115);
    lv_obj_set_y(ui_uiSetClawSwitch, 92);
    lv_obj_set_align(ui_uiSetClawSwitch, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Button27, ui_event_Button27, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button28, ui_event_Button28, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_armXSlider, ui_event_armXSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_armYSlider, ui_event_armYSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_armZSlider, ui_event_armZSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button30, ui_event_Button30, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button31, ui_event_Button31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button32, ui_event_Button32, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button33, ui_event_Button33, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiSetClawSwitch, ui_event_uiSetClawSwitch, LV_EVENT_ALL, NULL);

}
