// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC

#include "ui.h"

void ui_servoTestScreen_screen_init(void)
{
    ui_servoTestScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_servoTestScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel6 = lv_obj_create(ui_servoTestScreen);
    lv_obj_set_width(ui_Panel6, 144);
    lv_obj_set_height(ui_Panel6, 116);
    lv_obj_set_x(ui_Panel6, -65);
    lv_obj_set_y(ui_Panel6, 40);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label56 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label56, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label56, -5);
    lv_obj_set_y(ui_Label56, -40);
    lv_obj_set_align(ui_Label56, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label56, "舵机0:");
    lv_obj_set_style_text_font(ui_Label56, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -5);
    lv_obj_set_y(ui_Label7, -20);
    lv_obj_set_align(ui_Label7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label7, "舵机1:");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -5);
    lv_obj_set_y(ui_Label8, 0);
    lv_obj_set_align(ui_Label8, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label8, "舵机2:");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label53, -5);
    lv_obj_set_y(ui_Label53, 20);
    lv_obj_set_align(ui_Label53, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label53, "舵机3:");
    lv_obj_set_style_text_font(ui_Label53, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label54, -5);
    lv_obj_set_y(ui_Label54, 40);
    lv_obj_set_align(ui_Label54, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label54, "舵机4:");
    lv_obj_set_style_text_font(ui_Label54, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_servo0angle = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_servo0angle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo0angle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo0angle, 20);
    lv_obj_set_y(ui_servo0angle, -40);
    lv_obj_set_align(ui_servo0angle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo0angle, "0");

    ui_servo1angle = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_servo1angle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo1angle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo1angle, 20);
    lv_obj_set_y(ui_servo1angle, -20);
    lv_obj_set_align(ui_servo1angle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo1angle, "0");

    ui_servo2angle = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_servo2angle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo2angle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo2angle, 20);
    lv_obj_set_y(ui_servo2angle, 0);
    lv_obj_set_align(ui_servo2angle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo2angle, "0");

    ui_servo3angle = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_servo3angle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo3angle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo3angle, 20);
    lv_obj_set_y(ui_servo3angle, 20);
    lv_obj_set_align(ui_servo3angle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo3angle, "0");

    ui_servo4angle = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_servo4angle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo4angle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo4angle, 20);
    lv_obj_set_y(ui_servo4angle, 40);
    lv_obj_set_align(ui_servo4angle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo4angle, "0");

    ui_Button27 = lv_button_create(ui_servoTestScreen);
    lv_obj_set_width(ui_Button27, 100);
    lv_obj_set_height(ui_Button27, 50);
    lv_obj_set_x(ui_Button27, 95);
    lv_obj_set_y(ui_Button27, -85);
    lv_obj_set_align(ui_Button27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button27, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button27, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button27, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_Label10 = lv_label_create(ui_Button27);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "更新");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button28 = lv_button_create(ui_servoTestScreen);
    lv_obj_set_width(ui_Button28, 100);
    lv_obj_set_height(ui_Button28, 50);
    lv_obj_set_x(ui_Button28, -95);
    lv_obj_set_y(ui_Button28, -85);
    lv_obj_set_align(ui_Button28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button28, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button28, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button28, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);

    ui_Label13 = lv_label_create(ui_Button28);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "返回");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_servoTestScreen);
    lv_obj_set_width(ui_Panel2, 100);
    lv_obj_set_height(ui_Panel2, 94);
    lv_obj_set_x(ui_Panel2, 73);
    lv_obj_set_y(ui_Panel2, 40);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -20);
    lv_obj_set_y(ui_Label14, -25);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "x:");

    ui_Label15 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -20);
    lv_obj_set_y(ui_Label15, 0);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "y:");

    ui_Label16 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -20);
    lv_obj_set_y(ui_Label16, 25);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "z:");

    ui_armX = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_armX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_armX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_armX, 15);
    lv_obj_set_y(ui_armX, -25);
    lv_obj_set_align(ui_armX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_armX, "0");

    ui_armY = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_armY, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_armY, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_armY, 15);
    lv_obj_set_y(ui_armY, 0);
    lv_obj_set_align(ui_armY, LV_ALIGN_CENTER);
    lv_label_set_text(ui_armY, "0");

    ui_armZ = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_armZ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_armZ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_armZ, 15);
    lv_obj_set_y(ui_armZ, 25);
    lv_obj_set_align(ui_armZ, LV_ALIGN_CENTER);
    lv_label_set_text(ui_armZ, "0");

    lv_obj_add_event_cb(ui_Button27, ui_event_Button27, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button28, ui_event_Button28, LV_EVENT_ALL, NULL);

}
