// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color3);
    ui_object_set_themeable_style_property(ui_Screen1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color3);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 144);
    lv_obj_set_height(ui_Panel1, 84);
    lv_obj_set_x(ui_Panel1, -74);
    lv_obj_set_y(ui_Panel1, -73);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -39);
    lv_obj_set_y(ui_Label1, -24);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "当前x:");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -37);
    lv_obj_set_y(ui_Label4, -2);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "当前y:");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -26);
    lv_obj_set_y(ui_Label5, 22);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "当前Yaw:");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentX = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_currentX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currentX, 40);
    lv_obj_set_y(ui_currentX, -24);
    lv_obj_set_align(ui_currentX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_currentX, "0");

    ui_currentY = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_currentY, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentY, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currentY, 40);
    lv_obj_set_y(ui_currentY, -2);
    lv_obj_set_align(ui_currentY, LV_ALIGN_CENTER);
    lv_label_set_text(ui_currentY, "0");

    ui_currentYaw = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_currentYaw, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentYaw, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currentYaw, 40);
    lv_obj_set_y(ui_currentYaw, 22);
    lv_obj_set_align(ui_currentYaw, LV_ALIGN_CENTER);
    lv_label_set_text(ui_currentYaw, "0");

    ui_enableMotorSwitch = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_enableMotorSwitch, 50);
    lv_obj_set_height(ui_enableMotorSwitch, 25);
    lv_obj_set_x(ui_enableMotorSwitch, 92);
    lv_obj_set_y(ui_enableMotorSwitch, -96);
    lv_obj_set_align(ui_enableMotorSwitch, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_enableMotorSwitch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_enableMotorSwitch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);
    ui_object_set_themeable_style_property(ui_enableMotorSwitch, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_enableMotorSwitch, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);

    ui_object_set_themeable_style_property(ui_enableMotorSwitch, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_enableMotorSwitch, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 40);
    lv_obj_set_y(ui_Label6, -96);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "使能");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -128);
    lv_obj_set_y(ui_Label7, 103);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "电压:");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltage = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_voltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voltage, -83);
    lv_obj_set_y(ui_voltage, 106);
    lv_obj_set_align(ui_voltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltage, "12600");

    ui_Label8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -41);
    lv_obj_set_y(ui_Label8, 105);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "mV");

    ui_Button3 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button3, 50);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 102);
    lv_obj_set_y(ui_Button3, -51);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);

    ui_Label9 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "测试\n舵机");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button4, 50);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 43);
    lv_obj_set_y(ui_Button4, -50);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_Label11 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "舵机\n置零");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 126);
    lv_obj_set_height(ui_Panel2, 116);
    lv_obj_set_x(ui_Panel2, -82);
    lv_obj_set_y(ui_Panel2, 33);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -5);
    lv_obj_set_y(ui_Label10, -40);
    lv_obj_set_align(ui_Label10, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label10, "舵机0:");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -5);
    lv_obj_set_y(ui_Label13, -20);
    lv_obj_set_align(ui_Label13, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label13, "舵机1:");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -5);
    lv_obj_set_y(ui_Label14, 0);
    lv_obj_set_align(ui_Label14, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label14, "舵机2:");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -5);
    lv_obj_set_y(ui_Label15, 20);
    lv_obj_set_align(ui_Label15, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label15, "舵机3:");
    lv_obj_set_style_text_font(ui_Label15, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -5);
    lv_obj_set_y(ui_Label16, 40);
    lv_obj_set_align(ui_Label16, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label16, "舵机4:");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_servo0angle = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_servo0angle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo0angle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo0angle, 20);
    lv_obj_set_y(ui_servo0angle, -40);
    lv_obj_set_align(ui_servo0angle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo0angle, "0");

    ui_servo1angle = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_servo1angle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo1angle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo1angle, 20);
    lv_obj_set_y(ui_servo1angle, -20);
    lv_obj_set_align(ui_servo1angle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo1angle, "0");

    ui_servo2angle = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_servo2angle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo2angle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo2angle, 20);
    lv_obj_set_y(ui_servo2angle, 0);
    lv_obj_set_align(ui_servo2angle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo2angle, "0");

    ui_servo3angle = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_servo3angle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo3angle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo3angle, 20);
    lv_obj_set_y(ui_servo3angle, 20);
    lv_obj_set_align(ui_servo3angle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo3angle, "0");

    ui_servo4angle = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_servo4angle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_servo4angle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_servo4angle, 20);
    lv_obj_set_y(ui_servo4angle, 40);
    lv_obj_set_align(ui_servo4angle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_servo4angle, "0");

    ui_Button6 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button6, 50);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_x(ui_Button6, 44);
    lv_obj_set_y(ui_Button6, 13);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color2);
    ui_object_set_themeable_style_property(ui_Button6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color2);

    ui_Label17 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "OTA");

    ui_Button11 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button11, 50);
    lv_obj_set_height(ui_Button11, 50);
    lv_obj_set_x(ui_Button11, 102);
    lv_obj_set_y(ui_Button11, 13);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_color1);
    ui_object_set_themeable_style_property(ui_Button11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_color1);

    ui_Label12 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "底盘\n测试");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_enableMotorSwitch, ui_event_enableMotorSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);

}
