// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_lightest[1] = {0xE3FDFD};
const ui_theme_variable_t _ui_theme_alpha_lightest[1] = {255};

const ui_theme_variable_t _ui_theme_color_light[1] = {0xCBF1F5};
const ui_theme_variable_t _ui_theme_alpha_light[1] = {255};

const ui_theme_variable_t _ui_theme_color_middle[1] = {0xA6E3E9};
const ui_theme_variable_t _ui_theme_alpha_middle[1] = {255};

const ui_theme_variable_t _ui_theme_color_deep[1] = {0x71C9CE};
const ui_theme_variable_t _ui_theme_alpha_deep[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

