// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC_release

#include "ui.h"

void ui_taskcodeScr_screen_init(void)
{
    ui_taskcodeScr = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_taskcodeScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_taskcodePanel = lv_obj_create(ui_taskcodeScr);
    lv_obj_set_width(ui_taskcodePanel, 300);
    lv_obj_set_height(ui_taskcodePanel, 100);
    lv_obj_set_x(ui_taskcodePanel, 0);
    lv_obj_set_y(ui_taskcodePanel, -25);
    lv_obj_set_align(ui_taskcodePanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_taskcodePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_taskcodePanel, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_taskcodeText = lv_label_create(ui_taskcodePanel);
    lv_obj_set_width(ui_taskcodeText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_taskcodeText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_taskcodeText, 0);
    lv_obj_set_y(ui_taskcodeText, 1);
    lv_obj_set_align(ui_taskcodeText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_taskcodeText, "---+---");
    lv_obj_set_style_text_font(ui_taskcodeText, &ui_font_taskcode, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_taskProgressBar = lv_bar_create(ui_taskcodeScr);
    lv_obj_set_width(ui_taskProgressBar, 280);
    lv_obj_set_height(ui_taskProgressBar, 10);
    lv_obj_set_x(ui_taskProgressBar, 0);
    lv_obj_set_y(ui_taskProgressBar, 50);
    lv_obj_set_align(ui_taskProgressBar, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_taskProgressBar, lv_color_hex(0x71B3EB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taskProgressBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_taskProgressBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_taskProgressBar,
                                                                                                      lv_obj_get_style_pad_right(ui_taskProgressBar, LV_PART_MAIN) + 1, LV_PART_MAIN);

}
