// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_color1[1] = {0xEAC7C7};
const ui_theme_variable_t _ui_theme_alpha_color1[1] = {255};

const ui_theme_variable_t _ui_theme_color_color2[1] = {0xA0C3D2};
const ui_theme_variable_t _ui_theme_alpha_color2[1] = {255};

const ui_theme_variable_t _ui_theme_color_color3[1] = {0xF7F5EB};
const ui_theme_variable_t _ui_theme_alpha_color3[1] = {255};

const ui_theme_variable_t _ui_theme_color_color4[1] = {0xEAE0DA};
const ui_theme_variable_t _ui_theme_alpha_color4[1] = {255};

const ui_theme_variable_t _ui_theme_color_color5[1] = {0x000000};
const ui_theme_variable_t _ui_theme_alpha_color5[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

