// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button34 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button34, 150);
    lv_obj_set_height(ui_Button34, 50);
    lv_obj_set_x(ui_Button34, 0);
    lv_obj_set_y(ui_Button34, 60);
    lv_obj_set_align(ui_Button34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button34, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button34, lv_color_hex(0xA0C3D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label66 = lv_label_create(ui_Button34);
    lv_obj_set_width(ui_Label66, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label66, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label66, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label66, "put to material");

    ui_Button35 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button35, 150);
    lv_obj_set_height(ui_Button35, 50);
    lv_obj_set_x(ui_Button35, 0);
    lv_obj_set_y(ui_Button35, -60);
    lv_obj_set_align(ui_Button35, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button35, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button35, lv_color_hex(0xA0C3D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label67 = lv_label_create(ui_Button35);
    lv_obj_set_width(ui_Label67, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label67, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label67, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label67, "put to ground");

    ui_Button36 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button36, 150);
    lv_obj_set_height(ui_Button36, 50);
    lv_obj_set_align(ui_Button36, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button36, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button36, lv_color_hex(0xA0C3D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label68 = lv_label_create(ui_Button36);
    lv_obj_set_width(ui_Label68, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label68, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label68, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label68, "catch from ground");

    ui_Button37 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button37, 50);
    lv_obj_set_height(ui_Button37, 50);
    lv_obj_set_x(ui_Button37, -125);
    lv_obj_set_y(ui_Button37, -90);
    lv_obj_set_align(ui_Button37, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button37, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button37, lv_color_hex(0xEAC7C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label69 = lv_label_create(ui_Button37);
    lv_obj_set_width(ui_Label69, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label69, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label69, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label69, "返回");
    lv_obj_set_style_text_font(ui_Label69, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button34, ui_event_Button34, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button35, ui_event_Button35, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button36, ui_event_Button36, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button37, ui_event_Button37, LV_EVENT_ALL, NULL);

}
