// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC_release

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_startScr
void ui_startScr_screen_init(void);
lv_obj_t * ui_startScr;
void ui_event_startButton(lv_event_t * e);
lv_obj_t * ui_startButton;
lv_obj_t * ui_startButtonText;
lv_obj_t * ui_RPI;
lv_obj_t * ui_HWT101;
lv_obj_t * ui_PAW3395;
lv_obj_t * ui_Motor;
lv_obj_t * ui_Servo;
// CUSTOM VARIABLES

// SCREEN: ui_taskcodeScr
void ui_taskcodeScr_screen_init(void);
lv_obj_t * ui_taskcodeScr;
lv_obj_t * ui_taskcodePanel;
lv_obj_t * ui_taskcodeText;
lv_obj_t * ui_taskProgressBar;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_startButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        uiStartMainSequence(e);
        _ui_screen_change(&ui_taskcodeScr, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_taskcodeScr_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_startScr_screen_init();
    ui_taskcodeScr_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_startScr);
}
