// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC_release

#ifndef _EIC_RELEASE_UI_H
#define _EIC_RELEASE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_startScr
void ui_startScr_screen_init(void);
extern lv_obj_t * ui_startScr;
void ui_event_startButton(lv_event_t * e);
extern lv_obj_t * ui_startButton;
extern lv_obj_t * ui_startButtonText;
extern lv_obj_t * ui_RPI;
extern lv_obj_t * ui_HWT101;
extern lv_obj_t * ui_PAW3395;
extern lv_obj_t * ui_Motor;
extern lv_obj_t * ui_Servo;
// CUSTOM VARIABLES

// SCREEN: ui_taskcodeScr
void ui_taskcodeScr_screen_init(void);
extern lv_obj_t * ui_taskcodeScr;
extern lv_obj_t * ui_taskcodePanel;
extern lv_obj_t * ui_taskcodeText;
extern lv_obj_t * ui_taskProgressBar;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_bigchinese);
LV_FONT_DECLARE(ui_font_chinese);
LV_FONT_DECLARE(ui_font_taskcode);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
