// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: EIC_release

#include "ui.h"

void ui_startScr_screen_init(void)
{
    ui_startScr = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_startScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_startButton = lv_button_create(ui_startScr);
    lv_obj_set_width(ui_startButton, 250);
    lv_obj_set_height(ui_startButton, 100);
    lv_obj_set_x(ui_startButton, 0);
    lv_obj_set_y(ui_startButton, -25);
    lv_obj_set_align(ui_startButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_startButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_startButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_startButton, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_startButton, lv_color_hex(0x71B3EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_startButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startButtonText = lv_label_create(ui_startButton);
    lv_obj_set_width(ui_startButtonText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_startButtonText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_startButtonText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_startButtonText, "一键启动");
    lv_obj_set_style_text_font(ui_startButtonText, &ui_font_bigchinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPI = lv_checkbox_create(ui_startScr);
    lv_checkbox_set_text(ui_RPI, "R");
    lv_obj_set_width(ui_RPI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPI, 50);
    lv_obj_set_y(ui_RPI, 50);
    lv_obj_set_align(ui_RPI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RPI, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_RPI, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_border_color(ui_RPI, lv_color_hex(0x71B3EB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RPI, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPI, lv_color_hex(0x71B3EB), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_RPI, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_RPI, lv_color_hex(0x71B3EB), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_RPI, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_HWT101 = lv_checkbox_create(ui_startScr);
    lv_checkbox_set_text(ui_HWT101, "H");
    lv_obj_set_width(ui_HWT101, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HWT101, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HWT101, -100);
    lv_obj_set_y(ui_HWT101, 50);
    lv_obj_set_align(ui_HWT101, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HWT101, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_HWT101, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_border_color(ui_HWT101, lv_color_hex(0x71B3EB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HWT101, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HWT101, lv_color_hex(0x71B3EB), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_HWT101, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_HWT101, lv_color_hex(0x71B3EB), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_HWT101, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_PAW3395 = lv_checkbox_create(ui_startScr);
    lv_checkbox_set_text(ui_PAW3395, "P");
    lv_obj_set_width(ui_PAW3395, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PAW3395, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PAW3395, 0);
    lv_obj_set_y(ui_PAW3395, 50);
    lv_obj_set_align(ui_PAW3395, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PAW3395, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PAW3395, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_border_color(ui_PAW3395, lv_color_hex(0x71B3EB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PAW3395, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PAW3395, lv_color_hex(0x71B3EB), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PAW3395, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_PAW3395, lv_color_hex(0x71B3EB), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_PAW3395, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Motor = lv_checkbox_create(ui_startScr);
    lv_checkbox_set_text(ui_Motor, "M");
    lv_obj_set_width(ui_Motor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Motor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Motor, -50);
    lv_obj_set_y(ui_Motor, 50);
    lv_obj_set_align(ui_Motor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Motor, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Motor, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_border_color(ui_Motor, lv_color_hex(0x71B3EB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Motor, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Motor, lv_color_hex(0x71B3EB), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Motor, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_Motor, lv_color_hex(0x71B3EB), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Motor, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Servo = lv_checkbox_create(ui_startScr);
    lv_checkbox_set_text(ui_Servo, "S");
    lv_obj_set_width(ui_Servo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Servo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Servo, 100);
    lv_obj_set_y(ui_Servo, 50);
    lv_obj_set_align(ui_Servo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Servo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Servo, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_border_color(ui_Servo, lv_color_hex(0x71B3EB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Servo, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Servo, lv_color_hex(0x71B3EB), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Servo, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_Servo, lv_color_hex(0x71B3EB), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Servo, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_startButton, ui_event_startButton, LV_EVENT_ALL, NULL);

}
